# fly.toml file generated for smartforests-test on 2023-01-25T18:15:59+01:00

app = "smartforests-test"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"
  BASE_URL = "https://smartforests-test.fly.dev/"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "pipenv run bash .bin/release.sh"
  strategy = "rolling"

[[services]]
  # http_checks = []
  internal_port = 8080
  # processes = ["app"]
  protocol = "tcp"
  # script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [processes]
    web = "pipenv run bash .bin/run.sh"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"