# Generated by Django 3.2.6 on 2021-10-12 16:08

from django.db import migrations
import modelcluster.contrib.taggit
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0006_auto_20211007_1443'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='description',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storypage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='smartforests.AtlasTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
