version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3.11
        # [Choice] Install Node.js
        INSTALL_NODE: "true"
        NODE_VERSION: "18.19.1"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DEBUG=True

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: kartoza/postgis:16-3.4
    restart: unless-stopped
    volumes:
      - squad_postgres_db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DBNAME=postgres
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
    # Uncomment the below line and rebuild the container to log psql queries. View the log with:
    #
    #         docker exec smartforests_devcontainer-db-1 tail -f /var/lib/postgresql/13/main/pg_log/postgresql.log
    #
    #  - EXTRA_CONF=log_directory = 'pg_log'\nlog_filename = 'postgresql.log'\nlog_statement = 'all'\nlogging_collector = on

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  squad_postgres_db: {}
