# Generated by Django 3.2.6 on 2021-08-06 11:19

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('logbooks', '0004_alter_storypage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookPageIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('thumbnail_image', models.ImageField(
                    blank=True, null=True, upload_to='')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='index_entry', to='wagtailcore.page')),
                ('related_page_indexes', models.ManyToManyField(
                    related_name='related_to_page_indexes', to='logbooks.LogbookPageIndex')),
            ],
        ),
        migrations.AddIndex(
            model_name='logbookpageindex',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['metadata'], name='logbooks_lo_metadat_c0ce4b_gin'),
        ),
    ]
