# Generated by Django 3.2.6 on 2021-09-06 14:36

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0005_auto_20210806_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookpage',
            name='description',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
