# Generated by Django 3.2.6 on 2021-09-06 15:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0006_logbookpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='storypage',
            name='geographical_location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
