# Generated by Django 3.2.6 on 2021-09-17 15:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0007_auto_20210906_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyindexpage',
            options={'verbose_name': 'Logbook entries index page'},
        ),
        migrations.AlterModelOptions(
            name='storypage',
            options={'verbose_name': 'Logbook Entry', 'verbose_name_plural': 'Logbook Entries'},
        ),
        migrations.AddField(
            model_name='logbookpage',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='logbookpage',
            name='geographical_location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='importantpages',
            name='stories_index_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logbooks.storyindexpage', verbose_name='Logbook Entries Index Page'),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'link', 'ol', 'ul'], template='logbooks/story_blocks/text.html')), ('quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'])), ('author', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))])), ('embed', wagtail.core.blocks.RichTextBlock(features=['embed'], template='logbooks/story_blocks/text.html')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock())]))]),
        ),
    ]
