# Generated by Django 3.2.6 on 2021-10-07 14:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('logbooks', '0008_auto_20210917_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookEntryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('geographical_location', models.CharField(blank=True, max_length=250, null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('body', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'link', 'ol', 'ul'], template='logbooks/story_blocks/text.html')), ('quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'])), ('author', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))])), ('embed', wagtail.core.blocks.RichTextBlock(features=['embed'], template='logbooks/story_blocks/text.html')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock())]))])),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='atlastag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='atlastag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='importantpages',
            name='logbooks_index_page',
        ),
        migrations.RemoveField(
            model_name='importantpages',
            name='site',
        ),
        migrations.RemoveField(
            model_name='importantpages',
            name='stories_index_page',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='tags',
        ),
    ]
