# Generated by Django 3.2.6 on 2021-10-07 14:43

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('smartforests', '0005_atlastag_importantpages'),
        ('logbooks', '0009_auto_20211007_1443'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='smartforests.AtlasTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='AtlasTag',
        ),
        migrations.DeleteModel(
            name='ImportantPages',
        ),
        migrations.DeleteModel(
            name='StoryIndexPage',
        ),
        migrations.DeleteModel(
            name='StoryPage',
        ),
    ]
