# Generated by Django 3.2.8 on 2021-10-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0010_auto_20211018_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentrypage',
            name='indexed_streamfield_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
