# Generated by Django 3.2.6 on 2021-10-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0010_auto_20211007_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbookentrypage',
            options={'verbose_name': 'Logbook Entry', 'verbose_name_plural': 'Logbook Entries'},
        ),
        migrations.RemoveField(
            model_name='logbookpage',
            name='tags',
        ),
    ]
