# Generated by Django 3.2.8 on 2021-10-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('logbooks', '0011_alter_logbookentrypage_indexed_streamfield_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importantpages',
            name='stories_index_page',
        ),
        migrations.DeleteModel(
            name='StoryIndexPage',
        ),
    ]
