# Generated by Django 3.2.6 on 2021-10-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('smartforests', '0006_auto_20211007_1443'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('logbooks', '0013_logbookppage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogbookPPage',
        ),
    ]
