# Generated by Django 3.2.8 on 2021-10-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0005_mappage'),
        ('logbooks', '0013_storyindexpage_storypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartforests.cmsimage'),
        ),
    ]
