# Generated by Django 3.2.8 on 2021-10-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('smartforests', '0005_mappage'),
        ('logbooks', '0014_storypage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantpages',
            name='map_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartforests.mappage'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='menu_items',
            field=models.ManyToManyField(blank=True, related_name='_logbooks_importantpages_menu_items_+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='importantpages',
            name='stories_index_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logbooks.storyindexpage'),
        ),
    ]
