# Generated by Django 3.2.8 on 2021-10-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('logbooks', '0016_auto_20211028_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=list)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_cloud', to='taggit.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='tagcloud',
            index=models.Index(fields=['score'], name='logbooks_ta_score_b1cb1e_idx'),
        ),
    ]
