# Generated by Django 3.2.8 on 2021-10-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('logbooks', '0016_episodepage_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodepage',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
    ]
