# Generated by Django 3.2.8 on 2021-11-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('logbooks', '0017_auto_20211029_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcloud',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag_cloud', to='taggit.tag'),
        ),
    ]
