# Generated by Django 3.2.8 on 2021-10-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0015_auto_20211028_1317'),
        ('logbooks', '0017_alter_episodepage_audio'),
    ]

    operations = [
    ]
