# Generated by Django 3.2.8 on 2021-11-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0016_auto_20211028_1810'),
        ('logbooks', '0018_merge_20211028_1622'),
    ]

    operations = [
    ]
