# Generated by Django 3.2.9 on 2021-11-04 12:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail_footnotes.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('logbooks', '0019_merge_20211102_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodepage',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail_footnotes.blocks.RichTextBlockWithFootnotes(features=['h3', 'bold', 'italic', 'link', 'ol', 'ul', 'footnotes'], template='logbooks/story_blocks/text.html')), ('quote', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'])), ('author', wagtail.blocks.CharBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=False)), ('date', wagtail.blocks.DateBlock(required=False)), ('link', wagtail.blocks.URLBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock(template='logbooks/story_blocks/embed.html')), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.blocks.CharBlock())]))]),
        ),
        migrations.CreateModel(
            name='TagCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=list)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag_cloud', to='taggit.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='tagcloud',
            index=models.Index(fields=['score'], name='logbooks_ta_score_b1cb1e_idx'),
        ),
    ]
