# Generated by Django 3.2.9 on 2021-11-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0007_auto_20211104_1444'),
        ('logbooks', '0021_auto_20211104_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbookindexpage',
            options={'verbose_name': 'Logbooks index page'},
        ),
        migrations.AlterField(
            model_name='tagcloud',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag_cloud', to='smartforests.tag'),
        ),
        migrations.DeleteModel(
            name='LogbookPageIndex',
        ),
    ]
