# Generated by Django 3.2.9 on 2021-11-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0022_auto_20211105_1645'),
        ('logbooks', '0024_auto_20211104_1749'),
    ]

    operations = [
    ]
