# Generated by Django 3.2.9 on 2021-11-15 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logbooks', '0025_merge_0022_auto_20211105_1645_0024_auto_20211104_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributorpage',
            options={'verbose_name': 'Contributor'},
        ),
        migrations.AlterModelOptions(
            name='contributorsindexpage',
            options={'verbose_name': 'Contributors index page'},
        ),
        migrations.AlterField(
            model_name='contributorpage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
