# Generated by Django 3.2.9 on 2021-12-14 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logbooks', '0026_auto_20211115_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodepage',
            name='additional_contributing_users',
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, help_text='Contributors who have not directly edited this page', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logbookentrypage',
            name='additional_contributing_users',
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, help_text='Contributors who have not directly edited this page', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logbookpage',
            name='additional_contributing_users',
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, help_text='Contributors who have not directly edited this page', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storypage',
            name='additional_contributing_users',
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, help_text='Contributors who have not directly edited this page', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributorpage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='contributor_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('contributor_page', modelcluster.fields.ParentalKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='logbooks.contributorpage')),
            ],
        ),
        migrations.AddField(
            model_name='episodepage',
            name='additional_contributing_people',
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, help_text='Contributors who are not users of the Atlas', to='logbooks.Person'),
        ),
        migrations.AddField(
            model_name='logbookentrypage',
            name='additional_contributing_people',
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, help_text='Contributors who are not users of the Atlas', to='logbooks.Person'),
        ),
        migrations.AddField(
            model_name='logbookpage',
            name='additional_contributing_people',
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, help_text='Contributors who are not users of the Atlas', to='logbooks.Person'),
        ),
        migrations.AddField(
            model_name='storypage',
            name='additional_contributing_people',
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, help_text='Contributors who are not users of the Atlas', to='logbooks.Person'),
        ),
    ]
