# Generated by Django 3.2.9 on 2022-01-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0027_auto_20211214_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
    ]
