# Generated by Django 3.2.9 on 2022-01-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0028_alter_person_options'),
        ('logbooks', '0028_auto_20220107_1657'),
    ]

    operations = [
    ]
