# Generated by Django 3.2.12 on 2022-03-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0007_auto_20211104_1444'),
        ('logbooks', '0032_alter_episodepage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorpage',
            name='map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartforests.cmsimage'),
        ),
        migrations.AddField(
            model_name='episodepage',
            name='map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartforests.cmsimage'),
        ),
        migrations.AddField(
            model_name='logbookentrypage',
            name='map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartforests.cmsimage'),
        ),
        migrations.AddField(
            model_name='logbookpage',
            name='map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartforests.cmsimage'),
        ),
        migrations.AddField(
            model_name='storypage',
            name='map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartforests.cmsimage'),
        ),
    ]
