# Generated by Django 3.2.18 on 2023-06-01 12:33

from django.db import migrations
import logbooks.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0014_add_seo_metadata_to_map_page'),
        ('logbooks', '0036_add_radio_episode_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodepage',
            name='tags',
            field=logbooks.models.fields.LocalizedTaggableManager(
                blank=True, help_text='A comma-separated list of tags.', through='logbooks.AtlasTag', to='smartforests.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='logbookentrypage',
            name='tags',
            field=logbooks.models.fields.LocalizedTaggableManager(
                blank=True, help_text='A comma-separated list of tags.', through='logbooks.AtlasTag', to='smartforests.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='logbookpage',
            name='tags',
            field=logbooks.models.fields.LocalizedTaggableManager(
                blank=True, help_text='A comma-separated list of tags.', through='logbooks.AtlasTag', to='smartforests.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='tags',
            field=logbooks.models.fields.LocalizedTaggableManager(
                blank=True, help_text='A comma-separated list of tags.', through='logbooks.AtlasTag', to='smartforests.Tag', verbose_name='Tags'),
        ),
    ]
