# Generated by Django 3.2.18 on 2023-06-01 12:28

from django.db import migrations
import logbooks.models.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0037_auto_20230601_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodepage',
            name='endnotes',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logbookentrypage',
            name='endnotes',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storypage',
            name='endnotes',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
