# Generated by Django 3.2.18 on 2023-07-22 10:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0038_add_endnotes_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodepage',
            name='endnotes',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logbookentrypage',
            name='endnotes',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='endnotes',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
