# Generated by Django 3.2.25 on 2024-03-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0040_auto_20240216_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagCloud',
        ),
    ]
