# Generated by Django 3.2.25 on 2024-04-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0042_auto_20240425_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodepage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
