# Generated by Django 3.2.25 on 2024-04-26 09:51

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0044_playlistpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistpage',
            name='episodes',
        ),
        migrations.CreateModel(
            name='PlaylistPageEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='logbooks.episodepage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='logbooks.playlistpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
