# Generated by Django 3.2.25 on 2024-04-30 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_footnotes', '0002_alter_footnote_unique_together'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('smartforests', '0018_alter_taglink_unique_together'),
        ('wagtailmenus', '0023_remove_use_specific'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('logbooks', '0045_auto_20240426_0951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RadioHomePage',
            new_name='RadioArchivePage',
        ),
        migrations.AlterModelOptions(
            name='radioarchivepage',
            options={'verbose_name': 'Radio archive page'},
        ),
        migrations.AlterModelOptions(
            name='radioindexpage',
            options={'verbose_name': 'Radio home page'},
        ),
    ]
