# Generated by Django 3.2.25 on 2024-05-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0046_auto_20240430_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radioindexpage',
            options={'verbose_name': 'Radio index page'},
        ),
    ]
