# Generated by Django 3.2.25 on 2024-05-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0047_alter_radioindexpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodepage',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='logbookentrypage',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playlistpage',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storypage',
            name='citation',
            field=models.TextField(blank=True),
        ),
    ]
