# Generated by Django 3.2.25 on 2024-07-16 10:56

from django.db import migrations
import logbooks.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0019_alter_cmsimage_file'),
        ('logbooks', '0048_auto_20240516_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorsindexpage',
            name='group_by_tags',
            field=logbooks.models.fields.LocalizedTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='logbooks.AtlasTag', to='smartforests.Tag', verbose_name='Tags'),
        ),
    ]
