# Generated by Django 3.2.25 on 2024-07-16 11:13

from django.db import migrations
import logbooks.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0019_alter_cmsimage_file'),
        ('logbooks', '0049_contributorsindexpage_group_by_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorpage',
            name='tags',
            field=logbooks.models.fields.LocalizedTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='logbooks.AtlasTag', to='smartforests.Tag', verbose_name='Tags'),
        ),
    ]
