# Generated by Django 3.2.25 on 2024-08-07 15:56

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0050_contributorpage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='extract',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
