# Generated by Django 3.2.25 on 2024-08-21 14:56

from django.db import migrations, models
import logbooks.models.pages


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0019_alter_cmsimage_file'),
        ('logbooks', '0051_storypage_extract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyindexpage',
            options={'verbose_name': 'Stories Index Page'},
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_actions',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_address_country',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_address_locality',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_address_postal',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_address_region',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_address_street',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_extra_json',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_geo_lat',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_geo_lng',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_hours',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_image',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_logo',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_name',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_phone',
        ),
        migrations.RemoveField(
            model_name='storyindexpage',
            name='struct_org_type',
        ),
        migrations.AddField(
            model_name='contributorpage',
            name='past_contributor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contributorpage',
            name='tags',
            field=logbooks.models.pages.ContributorTaggableManager(help_text='A comma-separated list of tags.', through='logbooks.AtlasTag', to='smartforests.Tag', verbose_name='Tags'),
        ),
    ]
