# Generated by Django 3.2.25 on 2024-10-09 17:13

from django.db import migrations, models
import json

def replace_url_with_foreign_key(apps, schema_editor):
    TranslationSource = apps.get_model("wagtail_localize", "TranslationSource")
    for translation in TranslationSource.objects.all():
        content_json = json.loads(translation.content_json)
        if "thumbnail_image" not in content_json:
            continue

        Model = apps.get_model(translation.specific_content_type.app_label, translation.specific_content_type.model)
        instance = Model.objects.filter(
            translation_key=translation.object_id, locale_id=translation.locale_id
        ).first()
        if not instance:
            continue

        print(f"Fixing {instance}")
        if instance.thumbnail_image:
            content_json["thumbnail_image"] = instance.thumbnail_image.id
        else:
            content_json["thumbnail_image"] = None

        translation.content_json = json.dumps(content_json)
        translation.save()

def restore_url(apps, schema_editor):
    TranslationSource = apps.get_model("wagtail_localize", "TranslationSource")
    for translation in TranslationSource.objects.all():
        content_json = json.loads(translation.content_json)
        if "thumbnail_image" not in content_json:
            continue

        Model = apps.get_model(translation.specific_content_type.app_label, translation.specific_content_type.model)
        instance = Model.objects.filter(
            translation_key=translation.object_id, locale_id=translation.locale_id
        ).first()
        if not instance:
            continue

        print(f"Restoring {instance}")
        if instance.thumbnail_image:
            content_json["thumbnail_image"] = str(instance.thumbnail_image.file)
        else:
            content_json["thumbnail_image"] = ""

        translation.content_json = json.dumps(content_json)
        translation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0055_fix_revision_thumbnail_image'),
        ('wagtail_localize', '0016_rename_page_revision_translationlog_revision')
    ]

    operations = [
        migrations.RunPython(replace_url_with_foreign_key, restore_url)
    ]
