# Generated by Django 3.2.5 on 2021-08-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0003_cmsimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsimage',
            name='alt_text',
            field=models.CharField(default='', help_text="Describe this image as literally as possible. If you can close your eyes, have someone read the alt text to you, and imagine a reasonably accurate version of the image, you're on the right track.", max_length=1024),
        ),
    ]
