# Generated by Django 3.2.9 on 2021-11-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smartforests', '0005_mappage'),
    ]
    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100,
                 unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100,
                 unique=True, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(
            sql='''
                INSERT INTO smartforests_tag (id, name, slug)
                SELECT id, name, slug
                FROM taggit_tag
            ''',
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
