# Generated by Django 3.2.9 on 2021-11-04 13:02

from django.db import migrations, models


def _copy_tags(*args, **kwargs):
    try:
        from smartforests.models import Tag
        from smartforests.models import Tag as SFTag
    except ImportError:
        return

    SFTag.objects.bulk_create(
        SFTag(id=tag.id, slug=tag.slug, name=tag.name)
        for tag
        in Tag.objects.iterator()
    )


def _noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('smartforests', '0005_mappage'),
    ]
    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100,
                 unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100,
                 unique=True, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(code=_copy_tags, reverse_code=_noop)
    ]
