# Generated by Django 3.2.6 on 2021-10-07 14:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('smartforests', '0005_atlastag_importantpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantpages',
            name='stories_index_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stories.storyindexpage'),
        ),
        migrations.AddField(
            model_name='atlastag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='atlastag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartforests_atlastag_items', to='taggit.tag'),
        ),
    ]
