# Generated by Django 3.2.18 on 2023-04-24 14:07

from django.db import migrations
from wagtail.core.models import BootstrapTranslatableModel

class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0010_bootstrap_tag_translations'),
    ]

    operations = [
        BootstrapTranslatableModel('smartforests.Tag'),
    ]
