# Generated by Django 3.2.18 on 2023-04-24 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('smartforests', '0011_bootstrap_tag_translations_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('translation_key', 'locale')},
        ),
    ]
