# Generated by Django 3.2.25 on 2024-03-20 12:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0015_auto_20240216_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatedness', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_link', to='smartforests.tag')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_link', to='smartforests.tag')),
            ],
        ),
    ]
