# Generated by Django 3.2.25 on 2024-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0016_taglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='cached_page_count',
            field=models.IntegerField(default=0),
        ),
    ]
