# Generated by Django 3.2.25 on 2024-07-16 10:54

from django.db import migrations
import smartforests.models
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartforests', '0018_alter_taglink_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsimage',
            name='file',
            field=smartforests.models.CmsImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width'),
        ),
    ]
